[profile.default]
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'forge-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
test = 'test'
solc = '0.8.26'
fs_permissions = [{ access = 'read', path = './out' }, { access = 'read-write', path = './deploy-out' }]
evm_version = 'cancun'
ffi = true

[profile.dependencies]
openzeppelin-foundry-upgrades = { git = "https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades", rev = "dd9e5dd22b885b364354af6a1cbad8a36958e3df" }